return {
  'nvimdev/dashboard-nvim',
  event = 'VimEnter',
  config = function()
    require('dashboard').setup {
      theme = 'doom',
      config = {
        header = {
"                                  N0xdocccllllllcclokKN",
"                              WXOxxxxkO0KNNWWWWNXK0kxxxxkKN",
"                            NOddx0NW                 WNKkxdxON",
"                          Nkoox0KKKKKKKKXXXNWW            NOxoxKW",
"                        Xkl;lkOO00KKKKKKKKK000OO0NW          Xkod0W",
"                      XxoxOXW                WX0Okk0N          NOldX",
"      W0kX           WxoX N0kkkkkkkkkkO0KXW      WXOkkkOkkOXNW   Xdl0W",
"     Xo:kW           WxoXWxcx0KKKKK0OOOkkxxxk0N     WX0000OxokW   WklOW",
"    No'xW             NxoldK              NKOxdxKW         0oOW    Wkl0",
"    OlcxN              NllX                   NOoxN        NkoOW    WdlX",
"    0ooddON           WOckKKKKKKXNNW            XodX        WkdKW    Klk",
"    WKdxOxd0W       Xkdooxxxkxxxxdxkkkkk0N       XldN        W0kk0W  WdoN",
"     XxdXWxdN      0odKNKkON  N0kOXWNXKOxoxXW     OlO          WKoOW  xlK",
"  N0xxOXNOd0      WdoX0xddddxOOkKW WXKOk0x:okkk0XWWxlK          WkxN  klK",
"Nkdx0NWKdxX       WdoK00klkXxoK  N0kkkOXWk:ldl:::ldklcxkxkKW     0kN  klK",
"ddX  WkoOW         KdodxkKW Nkok0Ok0NNNKxlkXK0Okxo:'.,ldkolK     KON WdlX",
"oN   Oo0            KclX     W0xdxxxxxxdxKW       Nxcl:l0xoK     KKW XodW",
"dW   kdN            Nxo0WN00N    WWWWWW            WNo,x0okW     XX  OlO",
"lOW  KokNNXNW        WxlKNOxK                       XodkokN      NW NooN",
"0dx0XWKkxkdoK         klK                         W0ooloOW    WKKN Wkl0",
" N0kkOkdONxlK     WWXKl;dkkk0NW                   Kllx0N       XdkWKlxW",
"     WXodK0xONKkxxxkkxoolc:cddxX                 0lxN       WW Wdd0ooN",
"      WKkk0W 0:.;odxxko:oO0NWNKX                KlxW  WXOxxxxodxoxooX",
"             NkddkOKXWKlx                      KodNW0kxxxOKNNo.,clxX",
"                      NodW                 NKkdoxkkxxOXW    Wd:k0XW",
"                      WdlX          WNX0koccooodxx0N         0lO",
"                       Kook0KKK0Oxoc,'..  .:dxk0N      Xk0W  KlxW",
"                        WKko;;lxkkkdoooodxOKNW     WXOxdxX W0:;O",
"                          WO::x0XW           WWX0Okxxx0N   XxxdoK",
"                           WXl,oxkX       Kkxxxxxk0XW      WXOo:lOKW",
"                           NkcdNWXN       NXXNW         WXOxdx0X0kxxxxk0KN",
"                     WNXOkxdoodkKN                   N0kxxk0N      WX0kkxxx",
"                NKOxxxxxxOKNWWKkxddkKNW         WN0kxxxOXW               WK",
"             NOxdxkOKNW          NOloxxxk00K0OkxxxxkKW      WX0OOOOO00KN",
"           WOod0N                XddXWN0Oxc:dkOKNW       WKOOOO0KNNWWNNW",
"          WklOW                 KodN    WOd0W          XOkOKN",
"          WXX                  XodN    WxoK          N0OKW",
"                              WxoX    Wkl0         WX0XW",
"                              XlxW    0lkW         WNW",
"                              XkK   WWxoX",

        },
      },
    }
  end,
  dependencies = { { 'nvim-tree/nvim-web-devicons' } }
}
